services:
  - type: web
    name: my-static-site
    env: static
    repo: https://github.com/render-examples/sveltekit-static
    buildCommand: npm install && npm run build
    staticPublishPath: build